reps:
  wordreps:
    love: hate
    'yes': nope
    fuck: fudge
    my: me
    the: teh
    tony: tonayy
    crap: feces
    what: waht
    chris: kaneki
    shit: feces
    kyle: spud
    nerds: nubbz
    nerd: nubb
    hate: love
    hey: heyo
    you: yuo
    asshole: horsefucker
  msgreps:
    hey: konnichiwa
    we: we are the crystal gems
