main: me.tonayy.DevTestingPlugin
name: DevTestingPlugin
version: 1.0
description: Testing Only!
commands:
  hello:
    description: Replies with a greeting to the player!
    usage: /<command>
  spud:
    description: Surprise!
    usage: /<command>
  hof:
    description: Hall of Fame
    usage: /<command>
  pkmngo:
    description: Pokemon Go!
    usage: /<command>
  kek:
    description: kek kek kek
    usage: /<command>
  stahp:
    description: Disables Hall of Fame.
    usage: /<command>
  showhof:
    description: Enables Hall of Fame.
    usage: /<command>
  tony:
    description: Set player list name to current display name.
    usage: /<command>
  untony:
    description: Resets player list name to default username.
    usage: /<command>
  sudocmd:
    description: Makes player perform a command.
    usage: /<command> <player> <cmd>
  sudo:
    description: Makes player send a chat message or perform a command.
    usage: /<command> <player> <message>
  lolz:
    usage: /<command>
  allowrain:
    description: Enables/Disables any weather change to rain.
    usage: /<command> <on/off>
